#include <iostream>
// #include "Problem7.h"
// #include "Problem9.h"
// #include "Problem10.h"
// #include "Problem14.h"
// #include "Problem15.h"
// #include "Problem17.h"
// #include "Problem19.h"
// #include "Problem20.h"
// #include "Problem21.h"
// #include "Problem22.h"
// #include "Problem31.h"
// #include "Problem35.h"
// #include "Problem39.h"
// #include "Problem40.h"
// #include "Problem42.h"
// #include "problem43.h"
// #include "Problem47.h"
// #include "Problem48.h"
// #include "Problem16.h"
// #include "Problem18.h"
// #include "Problem19_.h"
// #include "Problem20_.h"
// #include "Problem21_.h"
// #include "Problem22_.h"
// #include "Problem23.h"
// #include "Problem31_.h"
// #include "Problem32.h"
// #include "Problem42_.h"
// #include "Problem43_.h"
// #include "Problem1.h"
// #include "Problem2.h"
// #include "Problem14_.h"
// #include "problem15_.h"
// #include "problem16_.h"
// #include "problem18_.h"
// #include "problem19_.h"
// #include "Problem20__.h"
// #include "Problem21__.h"
// #include "problem22__.h"
// #include "problem23_.h"
// #include "problem31__.h"
// #include "problem32_.h"
// #include "problem42__.h"
// #include "problem43__.h"
// #include "Problem4.h"
// #include "Problem8.h"
// #include "Problem11.h"
// #include "Problem24.h"
// #include "Problem49.h"
// #include "Problem33.h"
// #include "Problem34.h"
// #include "Problem36.h"
// #include "Problem44.h"
// #include "Problem45.h"
// #include "Problem36_.h"
// #include "Problem44_.h"
// #include "Problem45_.h"
// #include "problem26.h"
// #include "Problem27.h"
// #include "Problem28.h"
// #include "problem29.h"
// #include "problem30.h "
// #include "Problem32__.h"
// #include "problem46.h"
// #include "Problem26_.h"
// #include "Problem27_.h"
// #include "Problem28_.h"
// #include "Problem29_.h"
// #include "Problem30_.h  "
#include "Problem32____.h"

using namespace std;    

int main()
{
    Print();
    return 0;
}
